import assert from "node:assert/strict";
import mongoose from "mongoose";
import Ledger from "../models/WalletTransaction.js";
import { createWalletService, reconcileWalletEntries } from "../services/wallet.service.js";
import { approveRewardStatus } from "../services/reward-approval.service.js";
import { makeWalletHarness, walletUserId } from "./helpers/walletHarness.js";
const objectId = () => new mongoose.Types.ObjectId().toString();
const h = makeWalletHarness(); const wallet = createWalletService(h);
const credit = { userId: walletUserId, amount: 100, purpose: "REWARD_CREDIT", rewardId: objectId(), idempotencyKey: "credit-1" };
const first = await wallet.creditWallet(credit);
assert.equal(h.state.users[walletUserId].walletBalance, 100);
assert.equal(first.transaction.direction, "CREDIT"); assert.equal(first.transaction.balanceBefore, 0); assert.equal(first.transaction.balanceAfter, 100);
assert.equal((await wallet.creditWallet(credit)).transaction._id, first.transaction._id); assert.equal(h.state.entries.length, 1);
await assert.rejects(async () => wallet.creditWallet({ ...credit, amount: 101 }), /different operation/);
await assert.rejects(async () => wallet.creditWallet({ ...credit, rewardId: objectId() }), /different operation/);
const debit = { userId: walletUserId, amount: 60, purpose: "ORDER_PAYMENT", orderId: objectId(), idempotencyKey: "debit-1" };
const spent = await wallet.debitWallet(debit); await wallet.debitWallet(debit);
assert.equal(h.state.users[walletUserId].walletBalance, 40); assert.equal(h.state.entries.length, 2);
assert.equal(spent.transaction.balanceBefore, 100); assert.equal(spent.transaction.balanceAfter, 40);
await assert.rejects(wallet.debitWallet({ ...debit, amount: 50, idempotencyKey: "insufficient" }), /Insufficient/);
assert.equal(h.state.users[walletUserId].walletBalance, 40); assert.equal(h.state.entries.length, 2);
for (const amount of [0, -1, 0.1, NaN, Infinity, Number.MAX_SAFE_INTEGER + 1, "100"]) {
  await assert.rejects(async () => wallet.creditWallet({ ...credit, amount }), /whole-INR/);
}
await assert.rejects(async () => wallet.creditWallet({ ...credit, purpose: "ORDER_PAYMENT" }), /attribution/);
await assert.rejects(async () => wallet.creditWallet({ ...credit, userId: "invalid" }), /wallet user/);
await assert.rejects(wallet.creditWallet({ ...credit, session: { inTransaction: () => false } }), /active MongoDB/);
const reversal = { userId: walletUserId, transactionId: spent.transaction._id, idempotencyKey: "reverse-1", reason: "Cancel internal test debit" };
const restored = await wallet.reverseWalletTransaction(reversal);
assert.equal(restored.transaction.direction, "CREDIT"); assert.equal(restored.transaction.amount, 60);
assert.equal(h.state.users[walletUserId].walletBalance, 100);
assert.equal((await wallet.reverseWalletTransaction(reversal)).transaction._id, restored.transaction._id);
assert.equal((await wallet.reverseWalletTransaction({ ...reversal, idempotencyKey: "reverse-other-key" })).transaction._id, restored.transaction._id);
assert.equal(h.state.entries.length, 3);
await assert.rejects(wallet.reverseWalletTransaction({ ...reversal, transactionId: first.transaction._id }), /authorization/);
await assert.rejects(wallet.reverseWalletTransaction({ ...reversal, transactionId: restored.transaction._id }), /itself/);
const takeBack = await wallet.reverseWalletTransaction({ ...reversal, transactionId: first.transaction._id,
  idempotencyKey: "reverse-credit", reason: "Explicit test business correction", allowCreditReversal: true });
assert.equal(takeBack.transaction.direction, "DEBIT"); assert.equal(h.state.users[walletUserId].walletBalance, 0);
const dup = makeWalletHarness(); const dupWallet = createWalletService(dup);
await Promise.all([dupWallet.creditWallet(credit), dupWallet.creditWallet(credit)]);
assert.equal(dup.state.users[walletUserId].walletBalance, 100); assert.equal(dup.state.entries.length, 1);
const concurrent = makeWalletHarness({ balance: 500 }); const concurrentWallet = createWalletService(concurrent);
const debits = await Promise.allSettled([concurrentWallet.debitWallet({ ...debit, amount: 400, idempotencyKey: "400-a" }), concurrentWallet.debitWallet({ ...debit, amount: 400, idempotencyKey: "400-b" })]);
assert.equal(debits.filter((entry) => entry.status === "fulfilled").length, 1);
assert.equal(concurrent.state.users[walletUserId].walletBalance, 100); assert.equal(concurrent.state.entries.length, 1);
const rollback = makeWalletHarness(); rollback.state.failLedger = true;
await assert.rejects(createWalletService(rollback).creditWallet(credit), /ledger failure/);
assert.equal(rollback.state.users[walletUserId].walletBalance, 0); assert.equal(rollback.state.entries.length, 0);
const fractional = makeWalletHarness({ balance: 99.5 });
await assert.rejects(createWalletService(fractional).creditWallet(credit), /reconciliation/);
assert.equal(fractional.state.users[walletUserId].walletBalance, 99.5);
const otherId = objectId(); h.state.users[otherId] = { _id: otherId, walletBalance: 0 };
await wallet.creditWallet({ ...credit, userId: otherId, rewardId: objectId() });
assert.equal(h.state.users[otherId].walletBalance, 100, "keys are scoped by user");
const refund = await wallet.creditWallet({ userId: walletUserId, amount: 25, purpose: "ORDER_REFUND", orderId: objectId(), refundId: objectId(), idempotencyKey: "future-refund" });
assert.equal(refund.transaction.direction, "CREDIT");
const legacy = makeWalletHarness({ balance: 200 }); const legacyWallet = createWalletService(legacy);
await legacyWallet.creditWallet(credit);
const reconciliation = await legacyWallet.reconcileWallet({ userId: walletUserId });
assert.equal(reconciliation.currentBalance, 300); assert.equal(reconciliation.inferredOpeningBalance, 200);
assert.equal(reconciliation.ledgerDerivedBalance, null); assert.equal(reconciliation.historicalReconciliationComplete, false);
assert.equal((await legacyWallet.reconcileWallet({ userId: walletUserId, openingBalance: 200 })).matchesProvidedBaseline, true);
assert.equal(reconcileWalletEntries({ walletBalance: 301, entries: legacy.state.entries }).trackedBalanceMatches, false);
const admin = makeWalletHarness(); const rewardId = objectId();
admin.state.rewards.push({ _id: rewardId, user: walletUserId, type: "STORY", amount: 20, status: "Pending", creditedAt: null });
const approve = () => approveRewardStatus({ rewardId, status: "Approved", dependencies: admin.dependencies });
await Promise.all([approve(), approve()]);
assert.equal(admin.state.users[walletUserId].walletBalance, 20); assert.equal(admin.state.entries.length, 1);
assert.equal(admin.state.rewards[0].status, "Approved"); assert(admin.state.rewards[0].creditedAt);
assert.equal(admin.state.rewards[0].walletTransaction, admin.state.entries[0]._id);
await approveRewardStatus({ rewardId, status: "Rejected", dependencies: admin.dependencies }); await approve();
assert.equal(admin.state.users[walletUserId].walletBalance, 20, "status toggles cannot double-credit");
const adminFailure = makeWalletHarness(); adminFailure.state.failRewardSave = true;
adminFailure.state.rewards.push({ _id: rewardId, user: walletUserId, amount: 20, status: "Pending", creditedAt: null });
await assert.rejects(approveRewardStatus({ rewardId, status: "Approved", dependencies: adminFailure.dependencies }), /reward save/);
assert.equal(adminFailure.state.users[walletUserId].walletBalance, 0); assert.equal(adminFailure.state.entries.length, 0);
assert.equal(adminFailure.state.rewards[0].status, "Pending");
const old = makeWalletHarness({ balance: 20 });
old.state.rewards.push({ _id: rewardId, user: walletUserId, amount: 20, status: "Approved", creditedAt: new Date() });
await approveRewardStatus({ rewardId, status: "Approved", dependencies: old.dependencies });
assert.equal(old.state.entries.length, 0); assert.equal(old.state.users[walletUserId].walletBalance, 20);
old.state.rewards[0].creditedAt = null;
await assert.rejects(approveRewardStatus({ rewardId, status: "Approved", dependencies: old.dependencies }), /history requires reconciliation/);
await assert.rejects(approveRewardStatus({ rewardId, status: "Rejected", dependencies: old.dependencies }), /history requires reconciliation/);
assert.equal(old.state.rewards[0].status, "Approved");
const insufficientReversal = makeWalletHarness(); const reversalWallet = createWalletService(insufficientReversal);
const originalCredit = await reversalWallet.creditWallet(credit);
await reversalWallet.debitWallet(debit);
await assert.rejects(reversalWallet.reverseWalletTransaction({ userId: walletUserId, transactionId: originalCredit.transaction._id,
  idempotencyKey: "credit-reversal-insufficient", reason: "Authorized correction", allowCreditReversal: true }), /Insufficient/);
assert.equal(insufficientReversal.state.users[walletUserId].walletBalance, 40);
assert.equal(insufficientReversal.state.entries.length, 2);
const document = new Ledger({ user: walletUserId, reward: objectId(), purpose: "REWARD_CREDIT", direction: "CREDIT", amount: 100,
  balanceBefore: 0, balanceAfter: 100, idempotencyKey: "schema-test" });
await document.validate(); document.$isNew = false;
await assert.rejects(document.save(), /immutable/);
await assert.rejects(document.deleteOne(), /immutable/);
for (const operation of [() => Ledger.updateOne({}, { $set: { amount: 1 } }), () => Ledger.updateMany({}, {}),
  () => Ledger.findOneAndUpdate({}, {}), () => Ledger.replaceOne({}, {}), () => Ledger.findOneAndReplace({}, {}),
  () => Ledger.deleteOne({}), () => Ledger.deleteMany({}), () => Ledger.findOneAndDelete({}),
  () => Ledger.bulkWrite([{ deleteMany: { filter: {} } }]), () => Ledger.insertMany([])]) await assert.rejects(operation(), /immutable/);
for (const field of ["idempotencyKey", "reversalOf", "reward"]) assert(Ledger.schema.indexes().some(([fields, options]) => fields[field] === 1 && options.unique));
console.log("Wallet credits/debits, duplicate protection, conditional overspend, reward approval, reversals, legacy reconciliation and ledger immutability passed.");
console.log("Concurrency uses a serialized transaction/rollback mock with actual service code; real MongoDB contention was not tested.");
